# Generated by Django 3.0.8 on 2020-07-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='cv',
            field=models.FileField(default=1, upload_to='About/'),
            preserve_default=False,
        ),
    ]
